export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS';